name: Build and Test Spring Boot App

on:
  push:
    branches:
      - main
      - develop
      - master
      - release/*
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - develop
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and run tests
        run: mvn clean install
