name: Build, Test & SonarCloud

on:
  push:
    branches:
      - main
      - develop
      - master
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches: [develop, master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & Test
        run: ./mvnw -B -Pcoverage clean verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=usdot-fhwa-stol
            -Dsonar.projectKey=usdot-fhwa-stol_c2c-mvt
            -Dsonar.java.binaries=target
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.coverage.exclusions=src/main/resources/static/**,src/test/java/**,**/*Exception.java,**/C2CMVTApplication.java,**/ServletInitializer.java
            -Dsonar.newCode.referenceBranch=main